### ISSUE TITLE
Summarize text from variable

### ISSUE THREAD

**Issue by Fredehagelund92** [freekrai/summarizer#2]
I'm scraping article/texts and storing them in variables however it does not seem to work when i try to summarize this it returns the original_lenght = 1344 summary_length = 0 and summary ration = 100. Is there a way to summarize without using the ob_start and end?

**Comment by jankal** [comment]
Normally this should work using this code:
```php
<?php
$st = new Summarizer();
$summary = $st->get_summary($content);
echo $summary;
var_dump($st->how_we_did());
```
when you have your text in the content variable.
But make sure, it has paragraphs and sentences.
A paragraph is expressed as `"\r\n\r\n"` or `PHP_EOL . PHP_EOL`.

If this doesn't help, please post your code and I'll evaluate.

**Comment by freekrai** [comment]
Hi @Fredehagelund92 sorry I missed this, was busy with a few conferences :)

@jankal looks like he answered your question either way, so let me know if that worked for you :)

@jankal is correct that you would send the content to the `get_summary` function, I tend to use ob_start and end, but you can use any variable for it.

You can see this at work here: http://workerpod.com/ which is the site it was originally designed to be used with.

**Comment by buneme** [comment]
I'm having the same problem

**Comment by freekrai** [comment]
@buneme please post a sample of how you are using it?

If the content inside the variable doesn't have a paragraph then it might have trouble getting a proper summary as the algorithm used is based on paragraphs and then sentences inside paragraphs.

**Comment by jankal** [comment]
@buneme @freekrai What about closing this issue?
No one is responding anymore.
@buneme I expect you to respond with a code sample. Else we won't be able to help you with this!
